version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: pokemon-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    container_name: pokemon-frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend

